# Generated by Django 4.0.5 on 2022-07-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_comment_delete_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(default='comment here'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
